In [1]:
import cv2
import time
import numpy as np
img = cv2.imread("img\lena.png")

In [6]:
rows,cols = img.shape[:2]

#GetRotationMatrix2D(center angle scale)
M_rotation = cv2.getRotationMatrix2D((cols//2,rows//2),45,0.5)
print("Rotation Matrix")
print(M_rotation)
print()

#GetRotationMatrix
M_translate = np.array([[1,0,100],
                       [0,1,-50]],dtype = np.float32)
print("M_translate")
print(M_translate)
#旋轉
img_rotation = cv2.warpAffine(img,M_rotation,(cols,rows))
#平移
img_translate = cv2.warpAffine(img,M_translate,(cols,rows))

imgs = np.hstack((img_rotation,img_translate))

cv2.imshow("imgs",imgs)
cv2.waitKey(0)
cv2.destroyAllWindows()

Rotation Matrix
[[  0.35355339   0.35355339  74.98066402]
 [ -0.35355339   0.35355339 256.        ]]

M_translate
[[  1.   0. 100.]
 [  0.   1. -50.]]


In [ ]:
rows , cols = img.shape[:2]

pt1 = np.array([[50,50], [300,100], [200,300]], dtype=np.float32)
pt2 = np.array([[80,80], [330,150], [300,300]], dtype=np.float32)

M_affine = cv2.getAffineTransform(pt1,pt2)
img_affine = cv2.warpAffine(img,M_affine,(cols,rows))
# 在圖片上標記點

img_copy = img.copy()
for idx, pts in enumerate(pt1):
    pts = tuple(map(int, pts))
    cv2.circle(img_copy, pts, 3, (0, 255, 0), -1)
    cv2.putText(img_copy, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)

for idx, pts in enumerate(pt2):
    pts = tuple(map(int, pts))
    cv2.circle(img_affine, pts, 3, (0, 255, 0), -1)
    cv2.putText(img_affine, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)
    
img_show_affine = np.hstack((img_copy, img_affine))

cv2.imshow("imgs",img_show_affine)
cv2.waitKey(0)
cv2.destroyAllWindows()